"use strict";
exports.__esModule = true;
var EVENT_TYPES;
(function (EVENT_TYPES) {
    EVENT_TYPES["POPUP_MOUNTED"] = "POPUP_MOUNTED";
    EVENT_TYPES["TRANSACTION_SIGNED"] = "TRANSACTION_SIGNED";
    EVENT_TYPES["TRANSACTION_EXECUTED"] = "TRANSACTION_EXECUTED";
    EVENT_TYPES["SEND_TRANSACTION_DATA"] = "SEND_TRANSACTION_DATA";
    EVENT_TYPES["POPUP_CLOSED"] = "POPUP_CLOSED";
})(EVENT_TYPES = exports.EVENT_TYPES || (exports.EVENT_TYPES = {}));
