export enum EVENT_TYPES {
    POPUP_MOUNTED = 'POPUP_MOUNTED',
    SIGNER_FINISHED = 'SIGNER_FINISHED',
    TRANSACTION_SIGNED = 'TRANSACTION_SIGNED',
    TRANSACTION_EXECUTED = 'TRANSACTION_EXECUTED',
    SEND_TRANSACTION_DATA = 'SEND_TRANSACTION_DATA',
    POPUP_CLOSED = 'POPUP_CLOSED',
}
