export enum EVENT_TYPES {
    SIGNER_MOUNTED = 'SIGNER_MOUNTED',
    EXECUTOR_MOUNTED = 'EXECUTOR_MOUNTED',
    TRANSACTION_SIGNED = 'TRANSACTION_SIGNED',
    TRANSACTION_EXECUTED = 'TRANSACTION_SIGNED',
    SEND_TRANSACTION_DATA = 'SEND_TRANSACTION_DATA',
    POPUP_CLOSED = 'POPUP_CLOSED',
}
