name: 🔖 Checks if last commit is a version bump
description: "Checks if last commit is a version bump"

outputs:
  is_version_bump:
    description: "Is version bump"
    value: ${{ steps.version_bump_check.outputs.is_version_bump }}

runs:
  using: "composite"
  steps:
    - name: Check if version bump
      id: version_bump_check
      shell: bash
      run: |
        #!/bin/bash
        set -x
        commit_message=$(git log -1 --pretty=%B)
        if [[ "$commit_message" =~ ^[0-9]+\.[0-9]+\.[0-9]+\-.+\.[0-9]+$ ]]; then
          echo "Commit is a version bump"
          echo "is_version_bump=true" >> $GITHUB_OUTPUT
        else
          echo "Commit is not a version bump"
          echo "is_version_bump=false" >> $GITHUB_OUTPUT
        fi
