export enum SignatureRequestType {
    ETHEREUM_TRANSACTION = 'ETHEREUM_TRANSACTION',
    ETHEREUM_RAW = 'ETHEREUM_RAW',
    GOCHAIN_TRANSACTION = 'GOCHAIN_TRANSACTION',
    GOCHAIN_RAW = 'GOCHAIN_RAW',
    VECHAIN_TRANSACTION = 'VECHAIN_TRANSACTION',
    TRON_TRANSACTION = 'TRON_TRANSACTION',
    TRC10_TRANSACTION = 'TRC10_TRANSACTION',
}
