export enum TransactionRequestType {
    ETH_TRANSACTION = 'ETH_TRANSACTION',
    ETHEREUM_ERC20_TRANSACTION = 'ETHEREUM_ERC20_TRANSACTION',
    GO_TRANSACTION = 'GO_TRANSACTION',
    GOCHAIN_ERC20_TRANSACTION = 'GOCHAIN_ERC20_TRANSACTION',
    VET_TRANSACTION = 'VET_TRANSACTION',
    VECHAIN_VIP180_TRANSACTION = 'VECHAIN_VIP180_TRANSACTION',
    TRX_TRANSACTION = 'TRX_TRANSACTION',
    TRC10_TRANSACTION = 'TRC10_TRANSACTION',
    BTC_TRANSACTION = 'BTC_TRANSACTION',
    LTC_TRANSACTION = 'LTC_TRANSACTION',
}
